# Generated by Django 5.1.2 on 2025-05-09 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 9, 7, 16, 22, 175530)),
        ),
    ]
